// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using agborala.Data;

#nullable disable

namespace agborala.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240110195216_Terceiramigration")]
    partial class Terceiramigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("agborala.Model.Destino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("destino");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Uma das praias mais lindas do mundo",
                            Nome = "Fernando de Noronha"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Um dos destinos mais requisitados do Brasil",
                            Nome = "Gramado"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Visita ao Cristo Redentor",
                            Nome = "Rio de Janeiro"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
