// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using agborala.Data;

#nullable disable

namespace agborala.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240109120709_segundamigration")]
    partial class segundamigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("agborala.Model.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("senha");

                    b.HasKey("Id");

                    b.ToTable("clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "andre@recodepro.com",
                            Nome = "Andre",
                            Senha = "abc123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "beatriz@recodepro.com",
                            Nome = "Beatriz",
                            Senha = "cde456"
                        },
                        new
                        {
                            Id = 3,
                            Email = "carlos@recodepro.com",
                            Nome = "Carlos",
                            Senha = "fgh789"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
